### PR TITLE
Add support for extent=

### PR DESCRIPTION
**Pull request by astrofrog**
This works and tests should pass, but I need to add actual tests for this functionality.

### CODE REVIEW

**Comment by astrofrog** [comment]
Oops I just duplicated https://github.com/ChrisBeaumont/mpl-modest-image/pull/6

**Comment by astrofrog** [comment]
I'll combine this with #6 tomorrow

**Comment by astrofrog** [comment]
I've now merged this with #6 and significantly expanded ``test_extent`` to make sure we catch different special cases. I think this is good to go if tests pass on Travis.

**Comment by ChrisBeaumont** [comment]
Thanks @astrofrog @ppinard  -- sorry I missed this originally!

**Pull request merged**
